### ISSUE TITLE
xlm-roberta example?

### ISSUE THREAD

**Issue by yuchenlin** [awslabs/mlm-scoring#6]
Thank you for the amazing work. I am trying to use xlm models for scoring, but I got a bug like below for using xlm-roberta-base/large. 

```python
(base) bill@ink-molly:~/MickeyProbes$ python probe_generation/sent_scoring.py
/home/bill/anaconda3/lib/python3.7/site-packages/mxnet/optimizer/optimizer.py:167: UserWarning: WARNING: New optimizer gluonnlp.optimizer.lamb.LAMB is overriding existing optimizer mxnet.optimizer.optimizer.LAMB
  Optimizer.opt_registry[name].__name__))
WARNING:root:Model 'xlm-roberta-large' not recognized as an MXNet model; treating as PyTorch model
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 513/513 [00:00<00:00, 257kB/s]
Can't set hidden_size with value 1024 for XLMConfig {
  "architectures": [
    "XLMRobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "model_type": "xlm",
  "pad_token_id": 1
}

Traceback (most recent call last):
  File "probe_generation/sent_scoring.py", line 9, in <module>
    model, vocab, tokenizer = get_pretrained(ctxs, 'xlm-roberta-large')
  File "/home/bill/MickeyProbes/mlm-scoring/src/mlm/models/__init__.py", line 126, in get_pretrained
    model, loading_info = transformers.XLMWithLMHeadModel.from_pretrained(model_fullname, output_loading_info=True)
  File "/home/bill/anaconda3/lib/python3.7/site-packages/transformers/modeling_utils.py", line 854, in from_pretrained
    **kwargs,
  File "/home/bill/anaconda3/lib/python3.7/site-packages/transformers/configuration_utils.py", line 316, in from_pretrained
    return cls.from_dict(config_dict, **kwargs)
  File "/home/bill/anaconda3/lib/python3.7/site-packages/transformers/configuration_utils.py", line 403, in from_dict
    config = cls(**config_dict)
  File "/home/bill/anaconda3/lib/python3.7/site-packages/transformers/configuration_xlm.py", line 195, in __init__
    super().__init__(pad_token_id=pad_token_id, bos_token_id=bos_token_id, **kwargs)
  File "/home/bill/anaconda3/lib/python3.7/site-packages/transformers/configuration_utils.py", line 215, in __init__
    raise err
  File "/home/bill/anaconda3/lib/python3.7/site-packages/transformers/configuration_utils.py", line 212, in __init__
    setattr(self, key, value)
AttributeError: can't set attribute
```

I am not sure if it is a version issue. Would you please provide an example for running xlm in the code? Thanks!

**Comment by yuchenlin** [comment]
I fixed this by following the example of ALBERT and DistilBERT. One thing need to take care is the `xlm` prefix should chang to `xlm-roberta` for this case.

**Comment by BarahFazili** [comment]
@yuchenlin Can you plz post the XLM-R example here.
